$(SECURE_BOOT_SIGNING_KEY):
	@echo "Need to generate secure boot signing key."
	@echo "One way is to run this command:"
	@echo "$(ESPSECUREPY) generate_signing_key $@"
	@echo "Keep key file safe after generating."
	@echo "(See secure boot documentation for risks & alternatives.)"
	@exit 1

ifdef CONFIG_BOOTLOADER_CHECK_APP_SUM
CFLAGS += -DCONFIG_ENABLE_BOOT_CHECK_SUM=1
endif

ifdef CONFIG_BOOTLOADER_CHECK_APP_HASH
CFLAGS += -DCONFIG_ENABLE_BOOT_CHECK_SHA256=1
endif
