COMPONENT_SRCDIRS :=
COMPONENT_ADD_INCLUDEDIRS :=

ifdef CONFIG_SSL_USING_MBEDTLS 
COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := .
endif

ifdef CONFIG_SSL_USING_WOLFSSL 
COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := .
endif